version: '3.8'

services:
  backend:
    build:
      context: ./BE
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mssql
      - DB_USER=sa
      - DB_PASSWORD=123456
      - DB_NAME=BKASIM
    depends_on:
      - mssql
    volumes:
      - ./BE:/app
      - /app/node_modules

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=123456
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend

volumes:
  mssql_data: