import AppHeader from "@/components/Header/Header";
import NewsDetailContent from "@/components/News/NewsDetailContent";
import ButtonApp from "@/components/Button/ButtonApp";
import images from "@/assets/images";
import Container from "@/components/Container/Container";

export default function NewsDetailPage() {
    const content = `
📱 Giới thiệu sản phẩm...
🔥 AI tích hợp thông minh...
✅ Sạc nhanh 65W - 🔋 Đạt 70% pin chỉ trong 20 phút...
🧠 Trải nghiệm camera sắc nét...
📱 Giới thiệu sản phẩm...
🔥 AI tích hợp thông minh...
✅ Sạc nhanh 65W - 🔋 Đạt 70% pin chỉ trong 20 phút...
🧠 Trải nghiệm camera sắc nét...📱 Giới thiệu sản phẩm...
🔥 AI tích hợp thông minh...
✅ Sạc nhanh 65W - 🔋 Đạt 70% pin chỉ trong 20 phút...
🧠 Trải nghiệm camera sắc nét...📱 Giới thiệu sản phẩm...
🔥 AI tích hợp thông minh...
✅ Sạc nhanh 65W - 🔋 Đạt 70% pin chỉ trong 20 phút...
🧠 Trải nghiệm camera sắc nét...
  `;

    return (
        <Container bg="light">

            <NewsDetailContent
                image={images.post1}
                date="05/03/2025"
                author="longnguyen"
                title="Hãng Công Nghệ X Ra Mắt Điện Thoại Mới Với Công Nghệ AI Tích Hợp"
                content={content}
            />

            <ButtonApp size="lg" title="Chia sẻ" onClick={() => alert("Chia sẻ!")} />
        </Container>

    );
}
